// apps/public-site/src/app/components/Footer.tsx
import React from 'react';
import { useFooter } from './Footer.hooks';

export const Footer: React.FC = () => {
  const { siteTitle, currentYear, footerLinks } = useFooter();

  return (
    <footer className="bg-primary-3 text-white links-white pb-4 footer-1 py-5">
      <div className="container">
        <div className="row">
          
          {/* COLONNA 1: Contatti / Info */}
          <div className="col-lg-4 mb-4 mb-lg-0">
            <h5 className="mb-3 font-weight-bold">Contatti</h5>
            <ul className="list-unstyled">
              <li className="mb-2">
                <a href="mailto:info@example.com" className="text-white-50">info@{siteTitle.toLowerCase().replace(/\s/g, '')}.it</a>
              </li>
              <li className="text-white-50">
                Via della Libertà, Palermo
              </li>
            </ul>
          </div>

          {/* COLONNA 2: Link Utili */}
          <div className="col-lg-4 mb-4 mb-lg-0">
            <h5 className="mb-3 font-weight-bold">Link Utili</h5>
            <ul className="list-unstyled d-flex flex-column gap-2">
              {footerLinks.map((item, index) => (
                <li key={index}>
                  <a href={item.path} className="text-white-50 hover-white transition">
                    {item.label}
                  </a>
                </li>
              ))}
            </ul>
          </div>

          {/* COLONNA 3: Copyright */}
          <div className="col-lg-4 text-lg-right mt-4 mt-lg-0">
            <div className="mb-2">
               <span className="h5 font-weight-bold">{siteTitle}</span>
            </div>
            <small className="text-white-50">
                &copy; {currentYear} Tutti i diritti riservati.
            </small>
            <div className="mt-2">
               <small className="text-muted">Powered by JsonPages React</small>
            </div>
          </div>

        </div>
      </div>
    </footer>
  );
};

// libs/ui/src/lib/components/footer/footer.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ConfigService } from '@json-pages/data-access';

@Component({
  selector: 'lib-footer',
  standalone: true,
  imports: [CommonModule],
  template: `
    <footer class="bg-primary-3 text-white links-white pb-4 footer-1">
      <div class="container">
        <div class="row">
          <div class="col-xl-auto mr-xl-5 col-md-3 mb-4 mb-md-0">
            <h5 class="mb-2">Contatti</h5>
            <ul class="nav flex-row flex-md-column">
              <li class="nav-item mr-3 mr-md-0">
                <a href="mailto:info@canottieritrinacria.it" class="nav-link fade-page px-0 py-2">info@canottieritrinacria.it</a>
              </li>
            </ul>
          </div>
          <div class="col mt-4 mt-md-0 mt-lg-5 mt-xl-0 order-lg-3 order-xl-2">
            <h5 class="mb-2">Link Utili</h5>
            <ul class="nav flex-row flex-md-column">
              <li *ngFor="let item of config.menu" class="nav-item mr-3 mr-md-0">
                <a [href]="item.path" class="nav-link fade-page px-0 py-2">{{ item.label }}</a>
              </li>
            </ul>
          </div>
          <div class="col-lg mt-2 mt-md-5 mt-lg-0 order-lg-3 order-xl-4 text-lg-right">
            <small class="text-muted">
                &copy; 2024 {{ config.site?.title }}
            </small>
          </div>
        </div>
      </div>
    </footer>
  `
})
export class FooterComponent {
  public config = inject(ConfigService);
}
